/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tonnay_opencv_natives_OpenCVNative */

#ifndef _Included_com_tonnay_opencv_natives_OpenCVNative
#define _Included_com_tonnay_opencv_natives_OpenCVNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tonnay_opencv_natives_OpenCVNative
 * Method:    showImage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tonnay_opencv_natives_OpenCVNative_showImage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonnay_opencv_natives_OpenCVNative
 * Method:    loadImage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tonnay_opencv_natives_OpenCVNative_loadImage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonnay_opencv_natives_OpenCVNative
 * Method:    compareDualImages
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tonnay_opencv_natives_OpenCVNative_compareDualImages
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
