/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tonnay_opencv_natives_OpenCVProxy */

#ifndef _Included_com_tonnay_opencv_natives_OpenCVProxy
#define _Included_com_tonnay_opencv_natives_OpenCVProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tonnay_opencv_natives_OpenCVProxy
 * Method:    showImage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tonnay_opencv_natives_OpenCVProxy_showImage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tonnay_opencv_natives_OpenCVProxy
 * Method:    compareImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tonnay_opencv_natives_OpenCVProxy_compareImage
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
